/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface InjeolmiPoolInterface extends ethers.utils.Interface {
  functions: {
    "ijm()": FunctionFragment;
    "swapToIJM()": FunctionFragment;
    "addLiquidity()": FunctionFragment;
    "swapToKlay(uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "ijm", values?: undefined): string;
  encodeFunctionData(functionFragment: "swapToIJM", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addLiquidity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapToKlay",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "ijm", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swapToIJM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapToKlay", data: BytesLike): Result;

  events: {
    "SwapToIJM(address,uint256)": EventFragment;
    "SwapToKlay(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SwapToIJM"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SwapToKlay"): EventFragment;
}

export class InjeolmiPool extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: InjeolmiPoolInterface;

  functions: {
    ijm(overrides?: CallOverrides): Promise<[string]>;

    "ijm()"(overrides?: CallOverrides): Promise<[string]>;

    swapToIJM(overrides?: PayableOverrides): Promise<ContractTransaction>;

    "swapToIJM()"(overrides?: PayableOverrides): Promise<ContractTransaction>;

    addLiquidity(overrides?: PayableOverrides): Promise<ContractTransaction>;

    "addLiquidity()"(
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    swapToKlay(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "swapToKlay(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  ijm(overrides?: CallOverrides): Promise<string>;

  "ijm()"(overrides?: CallOverrides): Promise<string>;

  swapToIJM(overrides?: PayableOverrides): Promise<ContractTransaction>;

  "swapToIJM()"(overrides?: PayableOverrides): Promise<ContractTransaction>;

  addLiquidity(overrides?: PayableOverrides): Promise<ContractTransaction>;

  "addLiquidity()"(overrides?: PayableOverrides): Promise<ContractTransaction>;

  swapToKlay(
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "swapToKlay(uint256)"(
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    ijm(overrides?: CallOverrides): Promise<string>;

    "ijm()"(overrides?: CallOverrides): Promise<string>;

    swapToIJM(overrides?: CallOverrides): Promise<void>;

    "swapToIJM()"(overrides?: CallOverrides): Promise<void>;

    addLiquidity(overrides?: CallOverrides): Promise<void>;

    "addLiquidity()"(overrides?: CallOverrides): Promise<void>;

    swapToKlay(amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "swapToKlay(uint256)"(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    SwapToIJM(user: string | null, amount: null): EventFilter;

    SwapToKlay(user: string | null, amount: null): EventFilter;
  };

  estimateGas: {
    ijm(overrides?: CallOverrides): Promise<BigNumber>;

    "ijm()"(overrides?: CallOverrides): Promise<BigNumber>;

    swapToIJM(overrides?: PayableOverrides): Promise<BigNumber>;

    "swapToIJM()"(overrides?: PayableOverrides): Promise<BigNumber>;

    addLiquidity(overrides?: PayableOverrides): Promise<BigNumber>;

    "addLiquidity()"(overrides?: PayableOverrides): Promise<BigNumber>;

    swapToKlay(amount: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "swapToKlay(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ijm(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "ijm()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    swapToIJM(overrides?: PayableOverrides): Promise<PopulatedTransaction>;

    "swapToIJM()"(overrides?: PayableOverrides): Promise<PopulatedTransaction>;

    addLiquidity(overrides?: PayableOverrides): Promise<PopulatedTransaction>;

    "addLiquidity()"(
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    swapToKlay(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "swapToKlay(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
