/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ISparrowNFTs } from "../ISparrowNFTs";

export class ISparrowNFTs__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISparrowNFTs {
    return new Contract(address, _abi, signerOrProvider) as ISparrowNFTs;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];
