/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ISparrowStakingMix,
  ISparrowStakingMixInterface,
} from "../ISparrowStakingMix";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "totalNFTs",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "nft",
    outputs: [
      {
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "ids",
        type: "uint256[]",
      },
    ],
    name: "withdrawableReward",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "accRewardEach",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "id",
        type: "uint256",
      },
    ],
    name: "nftRewardDebt",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "PRECISION",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "mix",
    outputs: [
      {
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "ids",
        type: "uint256[]",
      },
    ],
    name: "withdrawReward",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        name: "id",
        type: "uint256",
      },
      {
        indexed: false,
        name: "withdrawedMix",
        type: "uint256",
      },
    ],
    name: "WithdrawReward",
    type: "event",
  },
];

export class ISparrowStakingMix__factory {
  static readonly abi = _abi;
  static createInterface(): ISparrowStakingMixInterface {
    return new utils.Interface(_abi) as ISparrowStakingMixInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISparrowStakingMix {
    return new Contract(address, _abi, signerOrProvider) as ISparrowStakingMix;
  }
}
