/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { KIP13, KIP13Interface } from "../KIP13";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

export class KIP13__factory {
  static readonly abi = _abi;
  static createInterface(): KIP13Interface {
    return new utils.Interface(_abi) as KIP13Interface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): KIP13 {
    return new Contract(address, _abi, signerOrProvider) as KIP13;
  }
}
