/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface InitialSaleReceiverInterface extends ethers.utils.Interface {
  functions: {
    "receiveNew()": FunctionFragment;
    "withdrawIjm()": FunctionFragment;
    "newIjm()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "initialSale()": FunctionFragment;
    "owner()": FunctionFragment;
    "isOwner()": FunctionFragment;
    "setInitialSale(address)": FunctionFragment;
    "setNewIjm(address)": FunctionFragment;
    "received(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "receiveNew",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawIjm",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "newIjm", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialSale",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "isOwner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setInitialSale",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "setNewIjm", values: [string]): string;
  encodeFunctionData(functionFragment: "received", values: [string]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "receiveNew", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawIjm",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "newIjm", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setInitialSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setNewIjm", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "received", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class InitialSaleReceiver extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: InitialSaleReceiverInterface;

  functions: {
    receiveNew(overrides?: Overrides): Promise<ContractTransaction>;

    "receiveNew()"(overrides?: Overrides): Promise<ContractTransaction>;

    withdrawIjm(overrides?: Overrides): Promise<ContractTransaction>;

    "withdrawIjm()"(overrides?: Overrides): Promise<ContractTransaction>;

    newIjm(overrides?: CallOverrides): Promise<[string]>;

    "newIjm()"(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    initialSale(overrides?: CallOverrides): Promise<[string]>;

    "initialSale()"(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    isOwner(overrides?: CallOverrides): Promise<[boolean]>;

    "isOwner()"(overrides?: CallOverrides): Promise<[boolean]>;

    setInitialSale(
      _initialSale: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setInitialSale(address)"(
      _initialSale: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setNewIjm(
      _newIjm: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setNewIjm(address)"(
      _newIjm: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    received(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    "received(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  receiveNew(overrides?: Overrides): Promise<ContractTransaction>;

  "receiveNew()"(overrides?: Overrides): Promise<ContractTransaction>;

  withdrawIjm(overrides?: Overrides): Promise<ContractTransaction>;

  "withdrawIjm()"(overrides?: Overrides): Promise<ContractTransaction>;

  newIjm(overrides?: CallOverrides): Promise<string>;

  "newIjm()"(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  initialSale(overrides?: CallOverrides): Promise<string>;

  "initialSale()"(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  isOwner(overrides?: CallOverrides): Promise<boolean>;

  "isOwner()"(overrides?: CallOverrides): Promise<boolean>;

  setInitialSale(
    _initialSale: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setInitialSale(address)"(
    _initialSale: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setNewIjm(
    _newIjm: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setNewIjm(address)"(
    _newIjm: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  received(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "received(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    receiveNew(overrides?: CallOverrides): Promise<void>;

    "receiveNew()"(overrides?: CallOverrides): Promise<void>;

    withdrawIjm(overrides?: CallOverrides): Promise<void>;

    "withdrawIjm()"(overrides?: CallOverrides): Promise<void>;

    newIjm(overrides?: CallOverrides): Promise<string>;

    "newIjm()"(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    initialSale(overrides?: CallOverrides): Promise<string>;

    "initialSale()"(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    isOwner(overrides?: CallOverrides): Promise<boolean>;

    "isOwner()"(overrides?: CallOverrides): Promise<boolean>;

    setInitialSale(
      _initialSale: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setInitialSale(address)"(
      _initialSale: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setNewIjm(_newIjm: string, overrides?: CallOverrides): Promise<void>;

    "setNewIjm(address)"(
      _newIjm: string,
      overrides?: CallOverrides
    ): Promise<void>;

    received(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    "received(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;
  };

  estimateGas: {
    receiveNew(overrides?: Overrides): Promise<BigNumber>;

    "receiveNew()"(overrides?: Overrides): Promise<BigNumber>;

    withdrawIjm(overrides?: Overrides): Promise<BigNumber>;

    "withdrawIjm()"(overrides?: Overrides): Promise<BigNumber>;

    newIjm(overrides?: CallOverrides): Promise<BigNumber>;

    "newIjm()"(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    initialSale(overrides?: CallOverrides): Promise<BigNumber>;

    "initialSale()"(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    isOwner(overrides?: CallOverrides): Promise<BigNumber>;

    "isOwner()"(overrides?: CallOverrides): Promise<BigNumber>;

    setInitialSale(
      _initialSale: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setInitialSale(address)"(
      _initialSale: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setNewIjm(_newIjm: string, overrides?: Overrides): Promise<BigNumber>;

    "setNewIjm(address)"(
      _newIjm: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    received(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "received(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    receiveNew(overrides?: Overrides): Promise<PopulatedTransaction>;

    "receiveNew()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    withdrawIjm(overrides?: Overrides): Promise<PopulatedTransaction>;

    "withdrawIjm()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    newIjm(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "newIjm()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    initialSale(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "initialSale()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "isOwner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setInitialSale(
      _initialSale: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setInitialSale(address)"(
      _initialSale: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setNewIjm(
      _newIjm: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setNewIjm(address)"(
      _newIjm: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    received(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "received(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
